apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{{ .Values.metadataName }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.appName }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.appName }}"
    spec:
      containers:
        - name: "{{ .Values.appName }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 8080

---
 
apiVersion: v1 
kind: Service 
metadata: 
  name: "{{ .Values.appName }}"
spec:
  selector:
    app: "{{ .Values.appName }}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080





